version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum update -y
      - yum install -y unzip wget
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
      - rm -rf terraform
      - unzip -o terraform_1.7.0_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform --version || { echo "Terraform installation failed"; exit 1; }
      - pip install awscli --upgrade
  pre_build:
    commands:
      - echo Building Lambda deployment packages...
      - cd src/lambda/order-validator
      - zip -r ../../../order_validator.zip .
      - cd ../order-fulfillment  
      - zip -r ../../../order_fulfillment.zip .
      - cd ../../../../../

  build:
    commands:
      - echo Starting Terraform deployment...
      - pwd
      - ls -la
      - cd terraform/
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo Build completed successfully
      - terraform output

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '.terraform/**/*'
