version: 0.2

env:
  variables:
    ENVIRONMENT: prod

phases:
  install:
    commands:
      - echo "Installing system dependencies..."
      - yum update -y
      - yum install -y unzip wget
      
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - wwget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
      - unzip -o terraform_1.7.0_linux_amd64.zip -d /tmp/
      - chmod +x /tmp/terraform
      - mv /tmp/terraform /usr/local/bin/
      - terraform --version
      - echo "Terraform installation completed"
      
      - echo "Preparing Lambda deployment packages..."
      - |
        # Create Lambda packages if source directories exist
        if [ -d "src/lambda/order-validator" ]; then
          cd src/lambda/order-validator
          zip -r ../../../modules/lambda/order_validator.zip .
          cd ../../../
        fi
        
        if [ -d "src/lambda/order-fulfillment" ]; then
          cd src/lambda/order-fulfillment  
          zip -r ../../../modules/lambda/order_fulfillment.zip .
          cd ../../../
        fi

  build:
    commands:
      - echo "Starting Terraform operations..."
      - cd terraform/
      - terraform init
      - terraform plan -out=tfplan -var="environment=$ENVIRONMENT"
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Terraform operation completed successfully"
      - terraform output || echo "No outputs available"

artifacts:
  files:
    - '**/*'
  name: terraform-artifacts

cache:
  paths:
    - '.terraform/**/*'