version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - curl -fsSL https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Running pre-build tasks...
      - echo Running unit tests...
      - python -m pytest tests/ -v
      - echo Building Lambda deployment packages...
      - cd src/lambda/order-validator
      - zip -r ../../../order_validator.zip .
      - cd ../order-fulfillment  
      - zip -r ../../../order_fulfillment.zip .
      - cd ../../..

  build:
    commands:
      - echo Starting Terraform deployment...
      - cd terraform
      - terraform init
      - terraform plan -var="environment=$ENVIRONMENT" -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo Build completed successfully
      - terraform output

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '.terraform/**/*'
