version: 0.2

env:
  variables:
    ENVIRONMENT: prod

phases:
  install:
    commands:
      - yum update -y
      - yum install -y unzip wget python3 python3-pip
      - yum install -y unzip wget
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
      - unzip -o terraform_1.7.0_linux_amd64.zip -d /tmp/
      - chmod +x /tmp/terraform
      - mv /tmp/terraform /usr/local/bin/
      - terraform --version || { echo "Terraform installation failed"; exit 1; }
      - pip install awscli --upgrade

  pre_build:
    commands:
      - echo "Building Lambda deployment packages..."
      - cd src/lambda/order-validator
      - zip -r ../../../order_validator.zip .
      - cd ../order-fulfillment  
      - zip -r ../../../order_fulfillment.zip .
      - cd ../../../

  build:
    commands:
      - echo "Starting Terraform deployment..."
      - pwd
      - ls -la
      - cd terraform/
      
      # Debug: Check what variables Terraform expects
      - echo "=== DEBUGGING TERRAFORM VARIABLES ==="
      - echo "Environment variable ENVIRONMENT = $ENVIRONMENT"
      - terraform --version
      - echo "Checking Terraform configuration..."
      - ls -la
      - cat variables.tf || echo "No variables.tf found"
      - echo "=== END DEBUG INFO ==="
      
      # Initialize
      - terraform init
      
      # Validate first to catch issues early
      - terraform validate
      
      # Add more debugging for the plan
      - echo "Running terraform plan with environment=$ENVIRONMENT"
      - terraform plan -out=tfplan 
      
      # Apply only if plan succeeds
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Build completed successfully"
      - cd terraform/
      - terraform output || echo "No outputs to display"

artifacts:
  files:
    - '**/*'
  name: terraform-artifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '.terraform/**/*'